image: registry.gitlab.com/respatialized/respatialized.gitlab.io:dev

pages:
  stage: deploy
  script:
    - (cd build && make all)
    - (cd build && make publish)
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
