image: clojure:openjdk-14-boot-alpine

before_script:
  - "apk update && apk add rsync"

pages:
  stage: deploy
  script:
    - boot build
    - rsync -r ./target/public ./public
  cache:
    paths:
      - public
      - .m2
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
