image: ubuntu:bionic

cache:
  paths:
    - .racket/

before_script:
  - apt-get update
  - apt-get install -y sqlite3 racket tidy texlive-xetex
  - raco pkg install pollen

pages:
  stage: deploy
  script:
    - make publish
  artifacts:
    paths:
      - public
  only:
    refs:
      - public
