image: registry.gitlab.com/respatialized/site:dev

cache:
  paths:
    - .racket/

pages:
  stage: deploy
  script:
    - make publish
  artifacts:
    paths:
      - public
  only:
    refs:
      - public
