image: alpine:latest

cache:
  paths:
    - .racket/

before_script:
  - apk add racket
  - raco pkg install pollen

pages:
  stage: deploy
  script:
    - make publish
  artifacts:
    paths:
      - public
  only:
    refs:
      - public
