image: clojure:openjdk-14-boot-alpine

variables:
  BOOT_LOCAL_REPO: $CI_PROJECT_DIR/.m2/repository

before_script:
  - "apk update && apk add rsync freetype"

pages:
  stage: deploy
  script:
    - boot build
    - rsync -r ./target/public/ ./public
  cache:
    paths:
      - public
      - $BOOT_LOCAL_REPO
  artifacts:
    paths:
      - public
  only:
    refs:
      - master
