* example org-mode file

this file exists for testing purposes. 

** rationale

adding org-mode to my own website's code is intended to reduce the impedance mismatch between Fabricate's (very powerful) markup and my ability to write plaintext quickly from anywhere. More ideas, expressed faster

#+begin_quote
It's also really hard to get better at having good ideas because you get such little feedback. It might take a year to build out a complex idea before finding out if it's good or not, which means you get maybe 40 attempts in your career.

But if you can try out 10 ideas a year then you get 400 attempts. Having 10x as much feedback is a huge advantage in learning any complex skill.
#+end_quote

Jamie Brandon, [[https://www.scattered-thoughts.net/writing/speed-matters/]["Speed Matters"]]

** example contents

taken from the [[https://github.com/200ok-ch/org-parser][org-parser]] repo, which has /surprisingly few/ complex examples of org syntax in action.


*This is bold*: Hello spec!

*Bold* text can also be just one word.

*This is also bold*: And here goes for some more text which even
 includes more *bold* statements.