name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-
      - name: Set up clojure
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.11.1.1208
      - name: Run site tests
        run: |
          clojure -X:dev:kaocha/test
