name: test
on: [push]
jobs:
  main:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install Clojure + tools-deps
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
      - name: Run Tests
        run: |
          clojure -X:dev:test:runner
